# Generated by Django 5.2.6 on 2026-04-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movielens_seed_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movie',
            new_name='movies_movi_source_78141e_idx',
            old_name='movies_movie_source__2bc5e6_idx',
        ),
    ]
