flowchart TD
    A[Clone repository] --> B[Create .env]
    B --> C[Install dependencies]
    C --> D[Create DB]
    D --> E[migrate]
    E --> F[seed_movielens]
    F --> G[enrich_tmdb_movies]
    G --> H[fetch_all_trailer_urls]
    H --> I[seed_rating_reviews]
    I --> J[fill_random_profile_data]
    J --> K[create_admin]
    K --> L[runserver]
